### ISSUE TITLE
[Suggestion] Add support for items renamed on an Anvil

### ISSUE THREAD

**Issue by seriosbrad** [alkarinv/BattleTracker#1]
As the title says, consider support for items renamed on an Anvil?

**Comment by alkarinv** [comment]
Yeah, I'll put in anvil support.  I've never used them though.. so what happens?

**Comment by seriosbrad** [comment]
You basically spend some XP Levels to repair an item on an anvil, while repairing you can rename it :)

**Comment by alkarinv** [comment]
oh interesting.  So the item gets renamed... i'll have to check this out and play with it. but consider it to be on the list!
