### ISSUE TITLE
Could not pass event EntityDeathEvent to BattleTracker v2.5.3

### ISSUE THREAD

**Issue by jkcgs** [alkarinv/BattleTracker#11]
2013-04-20 10:19:01 [SEVERE] Could not pass event EntityDeathEvent to BattleTracker v2.5.3
org.bukkit.event.EventException

> ```
>   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
>   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
>   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
>   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
>   at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:322)
>   at net.minecraft.server.v1_5_R2.EntityLiving.dropDeathLoot(EntityLiving.java:945)
>   at net.minecraft.server.v1_5_R2.EntityLiving.die(EntityLiving.java:893)
>   at net.minecraft.server.v1_5_R2.EntityLiving.damageEntity(EntityLiving.java:750)
>   at de.Keyle.MyPet.entity.types.EntityMyPet.damageEntity(EntityMyPet.java:203)
>   at net.minecraft.server.v1_5_R2.EntityHuman.attack(EntityHuman.java:874)
>   at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:1102)
>   at net.minecraft.server.v1_5_R2.Packet7UseEntity.handle(SourceFile:36)
>   at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
>   at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
>   at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
>   at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
>   at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:580)
>   at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
>   at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
>   at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
>   at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
> ```
> 
> Caused by: java.lang.NullPointerException
>       at mc.alk.tracker.listeners.BTEntityListener.ede(BTEntityListener.java:184)
>       at mc.alk.tracker.listeners.BTEntityListener.onEntityDeath(BTEntityListener.java:76)
>       at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source)
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>       at java.lang.reflect.Method.invoke(Unknown Source)
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
>       ... 20 more

Can't give more details, because I saw it on console :c

**Comment by alkarinv** [comment]
Here try this.

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

Let me know if it works.

**Comment by jkcgs** [comment]
Everything's ok :D

**Comment by alkarinv** [comment]
nice! let me know if it happens again
