### ISSUE TITLE
Not getting death messages (PvP and PvE)

### ISSUE THREAD

**Issue by clovisd** [alkarinv/BattleTracker#15]
None of the death messages are showing up when a player gets killed by the environment or another player.

I am running the latest BattleTracker plugin with Bukkit 1.5.1 R0.2.
What can I do?

Solved

**Comment by lorenzreweghs** [comment]
How did you solve it?
I have the same problem.

**Comment by lorenzreweghs** [comment]
Nevermind, the problem was the plugin "Healthbar" in my case.

**Comment by clovisd** [comment]
same, had that issue until I was going through my plugin configs and came across an option for health bar. Now, I don't even use health bar, just McMMO covers it just fine. Sorry I couldn't answer earlier.

**Comment by lorenzreweghs** [comment]
Do you know which option that was in Healthbar? Probably not, but I just ask it ;)
