### ISSUE TITLE
"You dont have permissions to create top sign"

### ISSUE THREAD

**Issue by welchts5** [alkarinv/BattleTracker#29]
Im an OP admin on creative yet I still get that error??? Any suggestions? Or what are the Permissions for it? Thanks

**Comment by alkarinv** [comment]
I'm using this code for that.

player.hasPermission("tracker.admin")

Usually that will be true if you have that perm or are an OP.  Sometimes if you use certain permission plugins (like PEX) they will make it so you need the perm even if you are OP.

**Comment by welchts5** [comment]
ok, so I should add tracker.admin to PEX under Admin (me)?

**Comment by alkarinv** [comment]
That's right.  Also I think PEX might have a way to switch off OP's needing perms, It's the only plugin I know of that does it in the first place.
