### ISSUE TITLE
Formatting problems and Overall Record stats.

### ISSUE THREAD

**Issue by mkromann** [alkarinv/BattleTracker#3]
There seems to a bug with the formatting for the command '/pvp vs <name>'. See here:
http://i.imgur.com/fOTfoer.png

In the same picture you can see that the Overall Record stats aren't displayed properly, it still says '(0 : 0 )'.

For the other player it is working though .. very weird:
http://i.imgur.com/P4tjuTg.png

**Comment by mkromann** [comment]
Maybe I should mention that 'Infuscu' (first image) was op when the killings took place. I tried to deop to see if it changed something but nothing.

Also I am using MySQL.

**Comment by alkarinv** [comment]
woah, that is weird.  hmm... why would he be exempt... his elo is alright ( i think ), so why the records...

Well thanks, I'll try and fix this.

**Comment by mkromann** [comment]
Yes, super weird.

I'll follow the ticket, so if you need anything .. :-)

**Comment by mkromann** [comment]
Question, what does elo mean?

**Comment by alkarinv** [comment]
Its just a rating between players.

A lot of games use it, but there are different ways to rate people.
