### ISSUE TITLE
BattleArena Stats not showing

### ISSUE THREAD

**Issue by matthiasiam** [alkarinv/BattleTracker#32]
BattleTracker seems to be working for all other stats besides BattleArena. It might be an issue with BattleArena however, cause when I play stats dont update after the username in the chat, no matter how many rounds or kills, it just shows **< username> [ 1250 ] /( 0:0 ) for every player.

Using spigot 1.7.2 and latest builds of your plugins as of the 6th of Feb.

**Comment by alkarinv** [comment]
Hmm,

so in the game configs for BattleArena, there is a section called rated.  Make sure rated is true.  Also what command are you typing to get the scores?

**Comment by matthiasiam** [comment]
That doesn't seem to change anything. I created a Skirmish match, which works great. However when anyone plays it, doesn't change any of the stats. Wins, ratio, etc. I am not using a command to get scores, in the chat it reads it back when the match ends. 
![screen shot 2014-02-06 at 8 35 37 pm](https://f.cloud.github.com/assets/6608496/2106762/561f622a-8fb1-11e3-83f2-189076ed9a9b.png)

![screen shot 2014-02-06 at 8 33 23 pm](https://f.cloud.github.com/assets/6608496/2106753/02347f74-8fb1-11e3-8125-61dbed929923.png)

**Comment by alkarinv** [comment]
After you change the rated: true, make sure you do a /ba reload.

Without that it won't reload by itself, also just a warning, the database for skirmish is "arena" but for most other games the database is set to the game name (all changeable of course)

**Comment by matthiasiam** [comment]
Yeah, I am aware of reloading, but I had no luck with it. I even restarted the server. :/ Reguardless of reloading though, the BattleArena plugin itself doesnt update its own scores per match. The first image above is like after 10 matches.

**Comment by alkarinv** [comment]
what's your ip?

**Comment by matthiasiam** [comment]
mc.matt-craft.co

**Comment by alkarinv** [comment]
Yep, it was the rated issue.  To make sure sometimes it's best to set through the command line.
- skirmish setOption rated true

cheers!

**Comment by matthiasiam** [comment]
Thanks again! Come back anytime! lol
