### ISSUE TITLE
Cannot create top signs - PEX disabled and using /op

### ISSUE THREAD

**Issue by alexpja** [alkarinv/BattleTracker#35]
Hey,

I am trying to create a ratings sign for [Arena] and even when I disable PEX and use normal /op /deop, it tells me that I don't have permission...

**Comment by alkarinv** [comment]
Hey Alex, I know the perms work (the code is just a method call to bukkit with the correct string... so there is literally nothing for me to change). I would do a restart and I bet you will have the permission if you are op.  PEX actually takes over even op permissions, so I would make sure to restart before checking.

<pre>
myplayer.hasPermission("whatever.node.to.check");
</pre>

**Comment by alexpja** [comment]
Nope. Restarted, still doesn't work. Is there a permission it assumes the user has?

**Comment by alkarinv** [comment]
"tracker.admin" is the perm I check for.

And I just added a check so that this will only be checked for non ops.  I'll release that version to bukkit.

**Comment by alexpja** [comment]
Added the perm via pex and works now :) thanks!

**Comment by alkarinv** [comment]
great!
