### ISSUE TITLE
Question: How can I connect BattleArena and BattleTracker?

### ISSUE THREAD

**Issue by alexpja** [alkarinv/BattleTracker#36]
Hi, sorry to bother.

Now that signs work, I was wondering if there is a setting that I need to set in order for BattleArena/Tracker to keep track of my rating and to increase it on win?

I cannot find documentation for the plugin :/

**Comment by alkarinv** [comment]
If they are both installed. Then it's already tracking those stats.  You can tell by doing.
- /&lt;game> top

Top signs can be created by doing

<pre>
[gametype]
whateverStat
</pre>

**Comment by alexpja** [comment]
Yeah I know that, but whenever we duel in the arena, the winning score isn't set or whatever. I assume both are supposed to work out of the box, but not for me..

**Comment by alkarinv** [comment]
Ahh, well I didn't want people racking up ratings on different games by dueling.  So by default that is off.

You need to go into BattleArena/config.yml and set allowRatedDuels: true

then add the rated to the default duel options.
