### ISSUE TITLE
Database Aren't Loading

### ISSUE THREAD

**Issue by niwong** [alkarinv/BattleTracker#38]
When I place down BattleTracker signs like [Arena] Top, all I get is the green "Updating".  This does not change, it seems like the databases aren't connected.  Is there a fix for this? 

Another problem that I have is when players complete PVP's their rating doesn't change, I already looked in the config.yml but could not find the fix.  I did turn TrackPVP to true.

**Comment by alkarinv** [comment]
Did you solve this? If you did I'm guessing no one had played an arena match?
