### ISSUE TITLE
'/spleef rank <player>' broken?

### ISSUE THREAD

**Issue by mkromann** [alkarinv/BattleTracker#4]
It seems like the command '/spleef rank BlockPark' insert 'Spleef' as the parameter no matter what. See when I type '/spleef rank BlockPark':

http://i.imgur.com/ttlX5B1.png

**Comment by alkarinv** [comment]
You need

http://dev.bukkit.org/server-mods/battletracker/

That will start adding stats, rankings etc.

**Comment by mkromann** [comment]
I've already got BattleTracker .. that's shouldn't be the issue afaik :-)

'/spleef rank' and '/spleef top' works just fine.
