### ISSUE TITLE
Stacktrace (?) [1.5]

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleTracker#5]
Seems to me like blowing up a regular TNT caused this... but after doing it again, it did not reoccur. Coincidence?

BT v2.4.1
BA v3.8.0

<pre>
03:13:22 [SEVERE]       at net.minecraft.server.v1_5_R1.MinecraftServer.q(MinecraftServer.java:471)
03:13:22 [SEVERE]       at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:403)
03:13:22 [SEVERE]       at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
03:13:22 [SEVERE] java.sql.SQLException: no such column: 'Flags'
03:13:22 [SEVERE]       at org.sqlite.RS.findColumn(RS.java:121)
03:13:22 [SEVERE]       at org.sqlite.RS.getInt(RS.java:293)
03:13:22 [SEVERE]       at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:275)
03:13:22 [SEVERE]       at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:275)
03:13:22 [SEVERE]       at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:275)
03:13:22 [SEVERE]       at mc.alk.tracker.serializers.SQLInstance.createStat(SQLInstance.java:326)
03:13:22 [SEVERE]       at mc.alk.tracker.serializers.SQLInstance.getRecord(SQLInstance.java:304)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:90)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:41)
03:13:22 [SEVERE]       at mc.alk.tracker.util.Cache.get(Cache.java:111)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.getRecord(TrackerImpl.java:116)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl._addStatRecord(TrackerImpl.java:143)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.access$000(TrackerImpl.java:41)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl$1.run(TrackerImpl.java:136)
03:13:22 [SEVERE]       at java.util.TimerThread.mainLoop(Unknown Source)
03:13:22 [SEVERE]       at java.util.TimerThread.run(Unknown Source)
03:13:22 [SEVERE] java.sql.SQLException: no such column: 'Flags'
03:13:22 [SEVERE]       at org.sqlite.RS.findColumn(RS.java:121)
03:13:22 [SEVERE]       at org.sqlite.RS.getInt(RS.java:293)
03:13:22 [SEVERE]       at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:275)
03:13:22 [SEVERE]       at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:275)
03:13:22 [SEVERE]       at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:275)
03:13:22 [SEVERE]       at mc.alk.tracker.serializers.SQLInstance.createStat(SQLInstance.java:326)
03:13:22 [SEVERE]       at mc.alk.tracker.serializers.SQLInstance.getRecord(SQLInstance.java:304)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:90)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:41)
03:13:22 [SEVERE]       at mc.alk.tracker.util.Cache.get(Cache.java:111)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.getRecord(TrackerImpl.java:116)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl._addStatRecord(TrackerImpl.java:144)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl.access$000(TrackerImpl.java:41)
03:13:22 [SEVERE]       at mc.alk.tracker.controllers.TrackerImpl$1.run(TrackerImpl.java:136)
03:13:22 [SEVERE]       at java.util.TimerThread.mainLoop(Unknown Source)
03:13:22 [SEVERE]       at java.util.TimerThread.run(Unknown Source)
</pre>

**Comment by alkarinv** [comment]
Its a database update issue.. should be fixed now.

http://dl.dropbox.com/u/38069770/jars/BattleTracker.jar
