### ISSUE TITLE
signs conflicting with essentials

### ISSUE THREAD

**Issue by xsonarx** [alkarinv/BattleTracker#9]
CB: 2725
Essentials: DEV.2.11.49

This crash happened when creating shops aka [buy] [sell].

Hopefully something can be done your side to stop this from conflicting with essentials shops?

Server Crash Error Log
http://pastebin.com/8Ci3ZUyx

**Comment by alkarinv** [comment]
I don't think this was an essentials or a BattleTracker error.

Here were the events that were happening at the time of the crash, doesnt look like either plugin to me.

net.minecraft.server.v1_5_R2.PathfinderGoalMoveThroughVillage::a (108 bytes)
Event: 39240.746 Thread 0x0000000001c79800 3376             net.minecraft.server.v1_5_R2.BlockFenceGate::k_ (12 bytes)
net.minecraft.server.v1_5_R2.BlockCobbleWall::updateShape (186 bytes)
Event: 39311.395 Thread 0x0000000001c79800 3378             net.minecraft.server.v1_5_R2.BlockCobbleWall::b (26 bytes)
Event: 39380.747 Thread 0x0000000001c76800 3379             net.minecraft.server.v1_5_R2.BlockCrops::d (3 bytes)

Also it might be a PermGen space issue.
PSPermGen       total 39616K, used 39223K [0x000000077ae00000, 0x000000077d4b0000, 0x0000000780000000)
  object space 39616K, 99% used [0x000000077ae00000,0x000000077d44dea8,0x000000077d4b0000)

Notice the fact that its 99% used up, which can cause the server to crash.

So you might need to expand your permgen space, its a java option you can specify when you start your server

**Comment by xsonarx** [comment]
The server is run from a host not my own computer. 

I did ask over at Essentials tickets first: https://www.assembla.com/spaces/essentials/support/tickets/3989

They provided me with the info leading me to battle tracker, and as it happened when creating a sign I'm not sure.
You can also see my plugin list on that ticket - if it provides any additional information.

**Comment by alkarinv** [comment]
Thanks for the ticket link. 

Did you happen to do a /reload? or something similar? That would explain a PrivilegedExceptionAction.

here is a dev version that check for null lines (which shouldn't happen but could technically)

http://dl.dropbox.com/u/38069770/jars/BattleTracker.jar

**Comment by xsonarx** [comment]
No reload, 1 person who was OP was doing essentials signs then the crash appeared from there.

it hasn't happened again yet(just the once), its random times i guess as i tired another sign and it was fine. Ill upload that version provided and come back with a debug log if it happens again.

Thank you

**Comment by alkarinv** [comment]
So this has happened multiple times?

**Comment by xsonarx** [comment]
nope just that once, Ive made a few more signs with essentials and it didn't crash or throw an error to console.

**Comment by alkarinv** [comment]
I honestly think it was some strange interaction, perhaps essentials and BattleTracker were both accessing the same sign at the same time... which could be possible if they were doing things asynchronously.

Anyway, reopen if this happens again, but between that new version and the circumstances I doubt it will.
